-- =========================================================
-- Barangay Cansangaya Household Information System
-- Database Setup
-- =========================================================
-- Create database if it does not exist
CREATE DATABASE IF NOT EXISTS bchis CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Use the database
USE bchis;

-- Set timezone to Asia/Manila
SET time_zone = '+08:00';

-- =========================================================
-- USERS TABLE
-- =========================================================
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    username VARCHAR(60) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM ('ADMIN', 'STAFF') NOT NULL DEFAULT 'STAFF',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );

-- Demo admin user (password: admin123)
-- Replace with real hash generated by PHP password_hash()
INSERT INTO users (full_name, username, password_hash, role) VALUES ('System Administrator', 'admin', '$2y$10$examplehashedpassword1234567890', 'ADMIN');

-- =========================================================
-- END OF SCHEMA
-- =========================================================